

scheduler:
  name: gridScheduler
  rate: 20

#scheduler_name: gridScheduler
#scheduler_period_seconds: 20
endpoint:
  geturl:  http://localhost:8081/dataservice/showRand
  posturl:  http://localhost:8081/dataservice/showRand

messagequeue:
  topic:
    name: blogposttopic